#pragma once

#define PROJECT_NAME "Bugdom2"
#define PROJECT_FULL_NAME "Bugdom 2"
#define PROJECT_VERSION "4.0.0"
#define PROJECT_VERSION_MAJOR 4
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
